spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minibank_db?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: p@ssword
    data: classpath:/schema.sql
    initialization-mode: always
